
export const ACTIONS = {
    RECEIVE_CURRENT_USER: "RECEIVE_CURRENT_USER",
    LOGOUT_CURRENT_USER: "LOGOUT_CURRENT_USER",
    REGISTER_NEW_USER: "REGISTER_NEW_USER",
    RECEIVE_ERRORS: "RECEIVE_ERRORS",
    DISMISS_ALERT_BOX: "DISMISS_ALERT_BOX",
    LOAD_COLLECTIONS: "LOAD_COLLECTIONS"
}
