export const MESSAGES = {
    'USER_LOGIN_SUCCESS': 'User have been logged in successfully',
    'USER_LOGIN_FAILURE_INCORRECT_PASSWORD': 'Incorrect password',
    'USER_LOGIN_FAILURE_INCORRECT_EMAIL': 'Provided email doesn\'t exists',
    'USER_LOGOUT_SUCCESS': 'user logged out successfully',
    'USER_LOGOUT_FAILURE': 'user couldn\'t be logged out',
    'USER_REGISTRATION_SUCCESS': 'user have been registered successfully, please login to continue',
    'USER_REGISTRATION_FAILURE_EMAIL_EXISTS': 'user registration failed, email already exists',
    'USER_REGISTRATION_FAILURE': 'user registration failed',
    "QUESTIONNAIRE_ADDITION_SUCCESS": "questionnaire was added successfully",
    "QUESTIONNAIRE_ADDITION_FAILURE": "questionnaire couldn\'t be added",
    "REQUEST_SUBMISSION_SUCCESS": "request to fill the questionnaire submitted successfully",
    "REQUEST_SUBMISSION_FAILURE": "request to fill the questionnaire couldn't be submitted",
};

export const RESPONSE_TYPES = {
    "USER_FETCH_FAILURE": "USER_FETCH_FAILURE",
    "USER_FETCH_SUCCESS": "USER_FETCH_SUCCESS",
    "USER_LOGIN_SUCCESS": "USER_LOGIN_SUCCESS",
    "USER_LOGIN_FAILURE": "USER_LOGIN_FAILURE",
    "USER_LOGOUT_SUCCESS": "USER_LOGOUT_SUCCESS",
    "USER_LOGOUT_FAILURE": "USER_LOGOUT_FAILURE",
    "USER_REGISTRATION_SUCCESS": "USER_REGISTRATION_SUCCESS",
    "USER_REGISTRATION_FAILURE": "USER_REGISTRATION_FAILURE",
    "QUESTIONNAIRE_ADDITION_SUCCESS": "QUESTIONNAIRE_ADDITION_SUCCESS",
    "QUESTIONNAIRE_ADDITION_FAILURE": "QUESTIONNAIRE_ADDITION_FAILURE",
    "QUESTIONNAIRE_FETCH_SUCCESS": "QUESTIONNAIRE_FETCH_SUCCESS",
    "QUESTIONNAIRE_FETCH_FAILURE": "QUESTIONNAIRE_FETCH_FAILURE",
    "REQUEST_SUBMISSION_SUCCESS": "REQUEST_SUBMISSION_SUCCESS",
    "REQUEST_SUBMISSION_FAILURE": "REQUEST_SUBMISSION_FAILURE"
}

