export const MESSAGES = {
    'USER_LOGIN_SUCCESS': 'User have been logged in successfully',
    'USER_LOGIN_FAILURE_INCORRECT_PASSWORD': 'Incorrect password',
    'USER_LOGIN_FAILURE_INCORRECT_EMAIL': 'Provided email doesn\'t exists',
    'USER_LOGOUT_SUCCESS': 'user logged out successfully',
    'USER_LOGOUT_FAILURE': 'user couldn\'t be logged out',
    'USER_REGISTRATION_SUCCESS': 'user have been registered successfully, please login to continue',
    'USER_REGISTRATION_FAILURE_EMAIL_EXISTS': 'user registration failed, email already exists',
    'USER_REGISTRATION_FAILURE': 'user registration failed',
    "COLLECTION_ADDITION_SUCCESS": "collection was added successfully",
    "COLLECTION_ADDITION_FAILURE": "collection couldn\'t be added",
    "REQUEST_SUBMISSION_SUCCESS": "request to fill the collection submitted successfully",
    "REQUEST_SUBMISSION_FAILURE": "request to fill the collection couldn't be submitted",
    "COLLECTION_PATCH_SUCCESS": "collection updated successfully",
    "COLLECTION_PATCH_FAILURE": "collection couldn\'t be updated",
    "COLLECTION_DELETE_SUCCESS": "collected deleted successfully",
    "COLLECTION_DELETE_FAILURE": "collection couln\'t be deleted"
};

export const RESPONSE_TYPES = {
    "USER_FETCH_FAILURE": "USER_FETCH_FAILURE",
    "USER_FETCH_SUCCESS": "USER_FETCH_SUCCESS",
    "USER_LOGIN_SUCCESS": "USER_LOGIN_SUCCESS",
    "USER_LOGIN_FAILURE": "USER_LOGIN_FAILURE",
    "USER_LOGOUT_SUCCESS": "USER_LOGOUT_SUCCESS",
    "USER_LOGOUT_FAILURE": "USER_LOGOUT_FAILURE",
    "USER_REGISTRATION_SUCCESS": "USER_REGISTRATION_SUCCESS",
    "USER_REGISTRATION_FAILURE": "USER_REGISTRATION_FAILURE",
    "COLLECTION_ADDITION_SUCCESS": "COLLECTION_ADDITION_SUCCESS",
    "COLLECTION_ADDITION_FAILURE": "COLLECTION_ADDITION_FAILURE",
    "COLLECTION_FETCH_SUCCESS": "COLLECTION_FETCH_SUCCESS",
    "COLLECTION_FETCH_FAILURE": "COLLECTION_FETCH_FAILURE",
    "COLLECTION_PATCH_SUCCESS": "COLLECTION_PATCH_SUCCESS",
    "COLLECTION_PATCH_FAILURE": "COLLECTION_PATCH_FAILURE",
    "COLLECTION_DELETE_SUCCESS": "COLLECTION_DELETE_SUCCESS",
    "COLLECTION_DELETE_FAILURE": "COLLECTION_DELETE_FAILURE",
    "REQUEST_SUBMISSION_SUCCESS": "REQUEST_SUBMISSION_SUCCESS",
    "REQUEST_SUBMISSION_FAILURE": "REQUEST_SUBMISSION_FAILURE"
}

